fixed Bank and Shop versions for log4j vuln

diff --git a/k8s_manifests/prod/app/deployments/app-loadgenerator.yaml b/k8s_manifests/prod/app/deployments/app-loadgenerator.yaml
--- a/k8s_manifests/prod/app/deployments/app-loadgenerator.yaml
+++ b/k8s_manifests/prod/app/deployments/app-loadgenerator.yaml
@@ -15,7 +15,6 @@ apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: loadgenerator
-  namespace: loadgenerator
 spec:
   selector:
     matchLabels:
@@ -28,14 +27,31 @@ spec:
       annotations:
         sidecar.istio.io/rewriteAppHTTPProbers: "true"
     spec:
+      serviceAccountName: default
       terminationGracePeriodSeconds: 5
       restartPolicy: Always
+      initContainers:
+      - command:
+        - /bin/sh
+        - -exc
+        - |
+          echo "Init container pinging frontend: ${FRONTEND_ADDR}..."
+          STATUSCODE=$(wget --server-response http://${FRONTEND_ADDR} 2>&1 | awk '/^  HTTP/{print $2}')
+          if test $STATUSCODE -ne 200; then
+              echo "Error: Could not reach frontend - Status code: ${STATUSCODE}"
+              exit 1
+          fi
+        name: frontend-check
+        image: busybox:latest
+        env:
+        - name: FRONTEND_ADDR
+          value: "frontend:80"
       containers:
       - name: main
         image: gcr.io/google-samples/microservices-demo/loadgenerator:v0.3.4
         env:
         - name: FRONTEND_ADDR
-          value: "frontend.frontend:80"
+          value: "frontend:80"
         - name: USERS
           value: "10"
         resources:
